{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  # PLACEHOLDER — generated by nixos-generate-config on the real hardware.
  #
  # To regenerate after first boot:
  #   sudo nixos-generate-config --show-hardware-config > hosts/alina/hardware-configuration.nix
  #
  # This file is intentionally minimal so the flake builds in CI / VMs
  # without requiring the physical machine.

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # Root filesystem — bcachefs on /dev/nvme0n1p2 (adjust partition if needed).
  # Disko handles the actual partitioning; this mirrors what nixos-generate-config
  # would emit after disko has run.
  fileSystems."/" = {
    device = "/dev/nvme0n1p2";
    fsType = "bcachefs";
  };

  fileSystems."/boot" = {
    device = "/dev/nvme0n1p1";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  # 22-core Intel laptop CPU
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
